[phases.install]
ignore = true

[phases.build]
cmds = ["cd medusa-backend && npm install -g pnpm@9.15.9 && pnpm install && pnpm build"]

[start]
cmd = "cd medusa-backend/apps/backend && npx medusa start"
